---
title: "WDI_UNESCO_Education_Data"
format: html
editor: visual
---

## Quarto

```{r}
library(dplyr)
library(tidyr)
```

```{r}
unesco_wide <- unesco_data %>%
  mutate(Level = case_when(
    indicatorId == "XSPENDP.02.FDPUB.FNCUR" ~ "PrePrimary (XSPENDP.02.FDPUB.FNCUR)",
    indicatorId == "XSPENDP.1.FDPUB.FNCUR"  ~ "Primary (XSPENDP.1.FDPUB.FNCUR)",
    indicatorId == "XSPENDP.2.FDPUB.FNCUR"  ~ "LowerSecondary (XSPENDP.2.FDPUB.FNCUR)",
    indicatorId == "XSPENDP.2T3.FDPUB.FNCUR" ~ "UpperSecondary (XSPENDP.2T3.FDPUB.FNCUR)",
    indicatorId == "XSPENDP.3.FDPUB.FNCUR"  ~ "Tertiary (XSPENDP.3.FDPUB.FNCUR)",
    indicatorId == "XSPENDP.4.FDPUB.FNCUR"  ~ "VocationalTraining (XSPENDP.4.FDPUB.FNCUR)",
    TRUE ~ indicatorId  # fallback in case of unexpected codes
  )) %>%
  select(-indicatorId) %>%
  pivot_wider(names_from = Level, values_from = value)

```

```{r}
unesco_wide <- unesco_wide %>%
  rename(iso3c = geoUnit)

unesco_wide <- unesco_wide %>%
  select(-qualifier, -magnitude)


edueco_joined <- edueco_data %>%
  left_join(unesco_wide, by = c("iso3c", "year"))

```

```{r}
head(edueco_joined)
```
